version: "3.9"
services:
  web:
    build: .
    volumes:
      - ./bin:/app/dist
    environment:
      - UID
      - GID
    command: /bin/sh -c "pyinstaller -F main.py -s -n detect -y --clean && chown -R ${UID}:${GID} dist"